<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="ORIGINAUTOMATION" name="com.origin.fractal.testauto.test.testsuites.WebTestsLogin" tests="4" failures="0" timestamp="01 Oct 2019 15:26:50 GMT" time="68.640" errors="1">
  <testcase name="testLogin" time="68.640" classname="com.origin.fractal.testauto.test.testsuites.WebTestsLogin">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.wv.auto.framework.utils.Reporter.writeFailure(Reporter.java:104)
at com.wv.auto.framework.utils.Reporter.writeSummary(Reporter.java:82)
at com.origin.fractal.testauto.test.testsuites.WebTestsLogin.testLogin(WebTestsLogin.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testLogin -->
  <testcase name="testLoginInvalid" classname="com.origin.fractal.testauto.test.testsuites.WebTestsLogin">
    <skipped/>
  </testcase> <!-- testLoginInvalid -->
  <testcase name="testLoginSearchLink" classname="com.origin.fractal.testauto.test.testsuites.WebTestsLogin">
    <skipped/>
  </testcase> <!-- testLoginSearchLink -->
  <testcase name="forgotPassword" classname="com.origin.fractal.testauto.test.testsuites.WebTestsLogin">
    <skipped/>
  </testcase> <!-- forgotPassword -->
</testsuite> <!-- com.origin.fractal.testauto.test.testsuites.WebTestsLogin -->
